### ISSUE TITLE
Ambiguous ids on join

### ISSUE THREAD

**Issue by cracker0dks** [jpravetz/node-datatable#16]
First of all: Very nice lib! I like it so far 👍 

Here is my issue... with:
`sFromSql : 'mitarbeiter LEFT JOIN personen ON personen.personId = mitarbeiter.personId'`

You will face an error if you want to render "personId" on the Datatable: (Column 'personId' in order clause is ambiguous)

This is true because the generated query looks like this: 
`'SELECT * FROM mitarbeiter LEFT JOIN personen ON personen.personId = mitarbeiter.personId ORDER BY personId asc LIMIT 0, 10'`
And _personId_ is in both tables

How can I go around this/fix it?

**Comment by jpravetz** [comment]
I haven't worked on SQL in a couple of years, so I'm too rusty to give a good answer. Sorry.

**Comment by cracker0dks** [comment]
thats very sad. In my opinion, you should start working on SQL again :D 
I solved this for the moment by not rendering the ID. If I need this to work at some point I will dig deeper or one day an other user steps by and solve this. Thanks again :)

**Comment by jpravetz** [comment]
Mongodb these days :-)

**Comment by cracker0dks** [comment]
this is not a lib problem. More sql. You can just define the columns instead of the star * and use SELECT personen.personenId AS ...
